x=(1,2,3,4,5,6,7,8,9,0)
print(len(x))
print(x)
print(max(x))
print(min(x))
x=(1,2,3,4,5,1,6,7,8,9,0)
num=list(x)
print(num)
num1=int(input("Enter a number"))
add=num.count(num1)
print(add)
x=tuple(num)
print(x)
x=(1,2,3,4,5,6,7,8,9)
y=int(input('enter a number'))
index=x.index(y)
print(index)
x=(1,2,3,4,5,6,7,8,9)
y=list(x)
print(y)
x=tuple(y)
print(x)
x=(1,2,3,4,5,6,7,8,9)
y=(1,2,3,4)
z=x+y
print(z)
x=(1,2,3,4,5,6,7,8,9)
y=int(input("Enter a number:"))
if y in x:
    print("The given element is exits")
else:
    print("y not in x")
fruit=('apple','mango','kiwwi')
(orange,cherry,banana)=fruit
print(orange)
print(cherry)
print(banana)
